project:
  type: website
  output-dir: docs

website:
  title: "Workshop Biocultural Restoration"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: partic.html
        text: Participants
      - href: dynamics.html
        text: Program
      - text: Working Contents
        menu: 
        - href: presentation.html
          text: Guide Slides
        - href: https://ecoaplic.org/slides_aulas/apresentacoes/biorestnet_workshop_kenya#/title-slide.html
          text: BioRestNet
        - href: https://www.canva.com/design/DAGHdeSPra8/bm-b7uwnBB0J875boM6jnA/view?utm_content=DAGHdeSPra8&utm_campaign=designshare&utm_medium=link&utm_source=editor
          text: Graphical Model
      - href: refs.html
        text: Suggested readings
      - href: drive.html
        text: Shared Folder
      - href: kenya_visa.html
        text: Getting to Kenya
      - href: weather.html
        text: Weather forecast
        

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



