project:
  type: website
  output-dir: docs

website:
  title: "Workshop Biocultural Restoration"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: partic.qmd
        text: Participants
      - href: dynamics.qmd
        text: Program
      - href: refs.qmd
        text: Suggested readings
      - href: kenya_visa.qmd
        text: Getting to Kenya
        

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



