project:
  type: website
  output-dir: docs

website:
  title: "Workshop Biocultural Restoration"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: partic.qmd
        text: Participants

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



