---
title: "Program"
---

This is a very short brief of what we planned for our workshop. The dynamics will mix speeches and collective discussions in breakout groups. 

## 3rd June
- Most of you might be travelling to Kenya

## 4th June
Arrival in the Hotel
- We won't be able to arrange pick-ups but Uber and Taxi works fine in Kenya or you can get in contact with [Panari Hotel](https://www.panarihotels.com/hotel-nairobi/) and arrange a shuttle service for you (recommended). 

- We also suggest to buy a SIM Card from Safaricom at the Nairobi airport if you want to stay connected. Kenya has good coverage even in the Savannah.

- Evening: refreshment in the Hotel bar

## 5th June

- 6 am transfer Nairobi to Mulot by shuttle bus service
- 1 pm:  transfer Mulot to Aitong in 4x4 vehicles
- Check-in in the [Enaitoti Hotel](https://www.tripadvisor.com/Hotel_Review-g19596053-d20062654-Reviews-Enaitoti_Hotel-Aitong_Rift_Valley_Province.html)

## 6th June -  Biocultural Approaches

|   Time  | Activity |
|---|---|
| 7-9 | Breakfast |
| 9-10 | Biocultural apporaches for landscape management -  **Felipe Melo & Antonio Uzal** 
|| Useful plants of the Maasai Mara - **Jedidah Nankaya**
|10-11 | Breakout groups - Biocultural Restoration: what it could means? | 
|11-12 | Sharing thoughts |
| 12-14 | Lunch | Winter |
| 14-16 | Traditional Ecological Knowledge - **Nivaldo Peroni** |
| | Landscape Biographies - **Raihana Ferdous** |
| 16-17 | Sharing thoughts |


## 7th June - Productive Restoration

|   Time  | Activity |
|---|---|
| 7-9 | Breakfast |
| 9-10 | Challenges of restoration of Maasai Mara ecosystems -  **Harrison Nebaala** 
|| Agroforestry for productive ecosystem restoration - **Ilyas Siddique**
|10-11 | Breakout groups - Biocultural Restoration: conciliating people's needs with biodiversity conservation | 
|11-12 | Sharing thoughts |
| 12-14 | Lunch | Winter |
| 14-16 | The health of the Earth skin - **Marcello Di Bonito** |
|  | TBC - **Christine Magaju** |
| 16-17 | Sharing thoughts |

## 8th June - Landscape Perspectives

|   Time  | Activity |
|---|---|
| 7-9 | Breakfast |
| 9-10 | Optimal landscapes for biodiversity -  **Voctor Arroyo** 
|| Monitoring soundscapes - **Antonio Uzal**
|10-11 | Breakout groups - Biocultural Restoration: social-ecological landscapes | 
|11-12 | Sharing thoughts |
| 12-14 | Lunch | Winter |
| 14-16 | Secondary growth of vegetation - **Madelon Lohbeck** |
|  | Landscape Biographies - **Raihana Ferdous** |
| 16-17 | Sharing thoughts |

## 9th June

- Safari Tour and visits to Maasai communities and conservancies
- Farewell party (after Safari)

## 10th June
- Transport to Nairobi

- Flight back to your country or Check-in in the [Enaitoti Hotel](https://www.tripadvisor.com/Hotel_Review-g19596053-d20062654-Reviews-Enaitoti_Hotel-Aitong_Rift_Valley_Province.html)
