---
title: "About this workshop"
---

The purpose of this document is to summarize the ideas around the organization of our workshop in Kenya that can help us to boost partnerships and research-action agendas. Ideas shared here will be incorporated into the applications we are planning for the future aiming to fund our research program in Kenya.

Background: The study of how working (human-modified) landscapes evolve is crucial to understand both human welfare and conservation challenges out of protected areas. Business-as-usual, area-based conservation approaches have been criticized for limited results to deliver environmental justice and protection for biodiversity. Rural population, mostly composed of so-called indigenous people and local communities (IPLC), safeguards most of the remaining natural areas under different kinds of management. Understanding how biodiversity and ecosystem services contribute to human wellbeing in these landscapes is amongst the most important conservation/restoration contributions for the sustainable development goals. The creation of networks of collaboration and knowledge sharing able to integrate both scientific and traditional ecological knowledge is an effective way to scale up the biocultural models of restoration and conservation that are, by definition, co-constructed by diverse stakeholders and actors drawing upon varying perspectives and specialities.

Aims: This proposal intends to seed-source the creation of a worldwide Network for Biocultural Restoration, starting from the enormous biological and cultural diversity of Kenyan social-ecological landscapes. 

Objective: The main objective is to promote a week-long workshop reuniting researchers with experience in the study of human-modified landscapes from multiple countries, representatives of traditional communities in Kenya and ONGs. The workshop will serve as a landmark for the launch of a coordinated network of researchers and practitioners on biocultural restoration of working landscapes.

Expected dynamics: The workshop will serve to share experiences and knowledge on how to set the principles of a large-scale, long-term and world-class research program that deliver both robust scientific knowledge and subsidies for the elaboration and implementation of evidence-based public policies that boost community-led management of social-ecological landscapes. 

Expected outputs: The main output of this workshop is the formalization of the BioRestNet - Network of Biocultural Restoration as a hub of diverse institutions and a research program based on the principles of sustainable management of landscapes and environmental justice.  We also aim to leave the workshop with a draft of a 'perspective paper' calling for the need of biocultural restoration.
